CREATE TABLE students (
    student_id VARCHAR(20) PRIMARY KEY,
    full_name VARCHAR(100),
    age INT,
    email VARCHAR(100),
    gender VARCHAR(10),
    course VARCHAR(100)
);

INSERT INTO students (student_id, full_name, age, email, gender, course) VALUES
('S2025-0503', 'Zachary Moore', 25, 'zachary.moore@university.edu', 'Male', 'BS Business Administration'),
('S2025-0504', 'Amber Sullivan', 25, 'amber.sullivan@university.edu', 'Female', 'BS Business Administration'),
('S2025-0505', 'Katelyn Taylor', 22, 'katelyn.taylor@university.edu', 'Female', 'BS Business Administration'),
('S2025-0506', 'David Leon', 24, 'david.leon@university.edu', 'Male', 'BS Business Administration'),
('S2025-0507', 'Lori Novak', 23, 'lori.novak@university.edu', 'Female', 'BS Business Administration'),
('S2025-0508', 'Beth Melendez', 25, 'beth.melendez@university.edu', 'Female', 'BS Business Administration'),
('S2025-0509', 'Richard Bolton', 19, 'richard.bolton@university.edu', 'Male', 'BS Business Administration'),
('S2025-0510', 'Jennifer Sanchez', 19, 'jennifer.sanchez@university.edu', 'Female', 'BS Business Administration'),
('S2025-0511', 'Stephanie Turner', 25, 'stephanie.turner@university.edu', 'Female', 'BS Business Administration'),
('S2025-0512', 'Jennifer Morales', 23, 'jennifer.morales@university.edu', 'Female', 'BS Business Administration'),
('S2025-0513', 'Rachel Martinez', 23, 'rachel.martinez@university.edu', 'Female', 'BS Business Administration'),
('S2025-0514', 'Stanley Rodriguez', 24, 'stanley.rodriguez@university.edu', 'Male', 'BS Business Administration'),
('S2025-0515', 'John Fox', 19, 'john.fox@university.edu', 'Male', 'BS Business Administration'),
('S2025-0516', 'Melissa Garza', 18, 'melissa.garza@university.edu', 'Female', 'BS Business Administration'),
('S2025-0517', 'Kimberly Smith', 19, 'kimberly.smith@university.edu', 'Female', 'BS Business Administration'),
('S2025-0518', 'Christina Garcia', 23, 'christina.garcia@university.edu', 'Female', 'BS Business Administration'),
('S2025-0519', 'Jason Peterson', 22, 'jason.peterson@university.edu', 'Male', 'BS Business Administration'),
('S2025-0520', 'Shawn Carter', 25, 'shawn.carter@university.edu', 'Male', 'BS Business Administration'),
('S2025-0521', 'Michelle Moon', 21, 'michelle.moon@university.edu', 'Female', 'BS Business Administration'),
('S2025-0522', 'Terri Rojas', 23, 'terri.rojas@university.edu', 'Female', 'BS Business Administration'),
('S2025-0523', 'Benjamin Riley', 18, 'benjamin.riley@university.edu', 'Male', 'BS Business Administration'),
('S2025-0524', 'Jimmy Holland', 19, 'jimmy.holland@university.edu', 'Male', 'BS Business Administration'),
('S2025-0525', 'Emily Booth', 20, 'emily.booth@university.edu', 'Female', 'BS Business Administration'),
('S2025-0526', 'Marie Montoya', 23, 'marie.montoya@university.edu', 'Female', 'BS Business Administration'),
('S2025-0527', 'Brian Jones', 17, 'brian.jones@university.edu', 'Male', 'BS Business Administration'),
('S2025-0528', 'William Blanchard', 17, 'william.blanchard@university.edu', 'Male', 'BS Business Administration'),
('S2025-0529', 'Gary Marquez', 21, 'gary.marquez@university.edu', 'Male', 'BS Business Administration'),
('S2025-0530', 'Emily Armstrong', 21, 'emily.armstrong@university.edu', 'Female', 'BS Business Administration'),
('S2025-0531', 'Nicole Mack', 25, 'nicole.mack@university.edu', 'Female', 'BS Business Administration'),
('S2025-0532', 'Dana Lane', 21, 'dana.lane@university.edu', 'Female', 'BS Business Administration'),
('S2025-0533', 'Christine Taylor', 23, 'christine.taylor@university.edu', 'Female', 'BS Business Administration'),
('S2025-0534', 'Lauren Smith', 17, 'lauren.smith@university.edu', 'Female', 'BS Business Administration'),
('S2025-0535', 'Jeffrey Park', 20, 'jeffrey.park@university.edu', 'Male', 'BS Business Administration'),
('S2025-0536', 'Danielle Harper', 19, 'danielle.harper@university.edu', 'Female', 'BS Business Administration'),
('S2025-0537', 'Colin Cook', 19, 'colin.cook@university.edu', 'Male', 'BS Business Administration'),
('S2025-0538', 'Michele Martin', 22, 'michele.martin@university.edu', 'Female', 'BS Business Administration'),
('S2025-0539', 'Megan Patterson', 20, 'megan.patterson@university.edu', 'Female', 'BS Business Administration'),
('S2025-0540', 'Mr. Andrew Rodriguez', 19, 'mr..andrew.rodriguez@university.edu', 'Male', 'BS Business Administration'),
('S2025-0541', 'Jacob Combs', 24, 'jacob.combs@university.edu', 'Male', 'BS Business Administration'),
('S2025-0542', 'Shawn Smith', 22, 'shawn.smith@university.edu', 'Male', 'BS Business Administration'),
('S2025-0543', 'Mary Torres', 20, 'mary.torres@university.edu', 'Female', 'BS Business Administration'),
('S2025-0544', 'Thomas Brown', 24, 'thomas.brown@university.edu', 'Male', 'BS Business Administration'),
('S2025-0545', 'Michael Scott', 25, 'michael.scott@university.edu', 'Male', 'BS Business Administration'),
('S2025-0546', 'Marissa Morrison', 18, 'marissa.morrison@university.edu', 'Female', 'BS Business Administration'),
('S2025-0547', 'Dana Sanders', 20, 'dana.sanders@university.edu', 'Female', 'BS Business Administration'),
('S2025-0548', 'Gail Harper', 17, 'gail.harper@university.edu', 'Female', 'BS Business Administration'),
('S2025-0549', 'Hannah Huff', 25, 'hannah.huff@university.edu', 'Female', 'BS Business Administration'),
('S2025-0550', 'Shawn Hicks', 19, 'shawn.hicks@university.edu', 'Male', 'BS Business Administration'),
('S2025-0551', 'Lauren Meyer', 19, 'lauren.meyer@university.edu', 'Female', 'BS Business Administration'),
('S2025-0552', 'Edward Rodriguez', 21, 'edward.rodriguez@university.edu', 'Male', 'BS Business Administration'),
('S2025-0553', 'Randy Davenport', 20, 'randy.davenport@university.edu', 'Male', 'BS Business Administration'),
('S2025-0554', 'Kevin Martinez', 17, 'kevin.martinez@university.edu', 'Male', 'BS Business Administration'),
('S2025-0555', 'Katherine York', 17, 'katherine.york@university.edu', 'Female', 'BS Business Administration');
